name: every_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.3
  package_data_server_api:
    path: ./package_data_server_api
  package_common:
    path: ./package_common
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cached_network_image: ^3.3.1
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7
  motion_toast: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.0.2



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
