name: package_data_server_api
description: "A data access layer module for app."
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_common:
    path: ../package_common
  json_annotation: ^4.9.0
  http_interceptor: ^2.0.0-beta.8
  freezed_annotation: ^2.4.4
  http: ^1.2.0
  json_serializable:  ^6.7.1   



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:  ^2.4.6



analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
